account/urls.py
from django.urls import path
from account.views import *
from django.urls import reverse_lazy
from django.contrib.auth import views as auth_views

app_name = 'account'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('signup/', signup_view, name='signup'),
    path('logout/', logout_view, name='logout'),
    path('password_reset/',auth_views.PasswordResetView.as_view(success_url=reverse_lazy('account:password_reset_done')),name='password_reset',),
    path('password_reset/done/',auth_views.PasswordResetDoneView.as_view(), name='password_reset_done',),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(success_url=reverse_lazy('account:password_reset_complete')),name='password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(),name='password_reset_complete',),
]

blog/urls.py
from django.urls import path
from blog.views import *

app_name='blog'

urlpatterns = [
    path('',blog_view,name='blog'),
    path('post-<int:pid>',blog_detail_view,name='blog-detail'),
    path('search/',blog_search ,name='search'),
    path('tag-<str:tag_str>',blog_tags ,name='tag'),
    path('category-<str:cat_str>',blog_category ,name='category'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import BlogSitemap
from mywebsite.sitemaps import StaticViewSitemap

sitemaps = {
    "static": StaticViewSitemap,
    'blog':BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mywebsite.urls')),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('captcha/', include('captcha.urls')), 
    path("robots.txt", include("robots.urls")),
    path("sitemap.xml",sitemap,{"sitemaps": sitemaps},name="django.contrib.sitemaps.views.sitemap",),
]
handler404 = 'mysite.views.custom_page_not_found'
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mywebsite/urls.py
from django.urls import path
from mysite.views import *

app_name = 'mywebsite'

urlpatterns = [
    path('',index_view,name='index'),
    path('contact/',contact_view,name='contact'),
    path('about/',about_view,name='about'),
    path('newsletter/',newsletter_view,name='newsletter')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db import models
from taggit.managers import TaggableManager
# Create your models here.
class category (models.Model) :
    name=models.CharField(max_length=255)
    def __str__(self):
        return self.name
class post (models.Model):
    image=models.ImageField( upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title = models.CharField(max_length=250)
    content = models.TextField()
    tags = TaggableManager()
    category = models.ManyToManyField(category)
    counted_views = models.IntegerField(default=0)
    counted_comments = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse("blog:blog-detail", kwargs={"pid": self.id})
def __str__(self):
        return self.id
class comment (models.Model) :
    post=models.ForeignKey(post,on_delete=models.CASCADE)
    name=models.CharField(max_length=250)
    email=models.EmailField()
    subject=models.CharField(max_length=250)
    message=models.TextField()
    status = models.BooleanField(default=False)
    login_require=models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.name

blog/forms.py
from django import forms
from blog.models import comment
class commentform(forms.ModelForm):
    class Meta :
        model=comment
        fields=['name','email','subject','message','post']

blog/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator,EmptyPage
from django.utils import timezone
from blog.models import post,comment,category
from blog.forms import commentform
from django.contrib import messages

# Create your views here.
def blog_view(request):
    posts=post.objects.filter(published_date__lte=timezone.now(),status=1)
    posts=Paginator(posts,3)
    try:
        page_number=request.GET.get('page')
        posts=posts.get_page(page_number)
    except EmptyPage :
        posts=posts.get_page(1)
    categories = category.objects.all().distinct()
    return render(request,'blog.html',{'posts':posts,'categories':categories})
def blog_detail_view(request,pid):
    t=comment.objects.filter(post=pid,status=1).count()
    posts=get_object_or_404(post,pk=pid,published_date__lte=timezone.now(),status=1)
    posts.counted_views+=1
    posts.counted_comments=t
    posts.save()
    postss=post.objects.filter(published_date__lte=timezone.now(),status=1)
    try:
        prev_post = post.objects.filter(published_date__lte=timezone.now(),status=1,pk__lt=pid).order_by('-pk').first()
    except post.DoesNotExist:
        prev_post = None

    try:
        next_post = post.objects.filter(published_date__lte=timezone.now(),status=1,pk__gt=pid).order_by('pk').first()
    except post.DoesNotExist:
        next_post = None
        
    comments=comment.objects.filter(post=pid).order_by('created_date')
    if request.method=='POST':
        form=commentform(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post = posts
            new_comment.save()
            messages.add_message(request,messages.SUCCESS,'your submit is successful')
        else:
           messages.add_message(request,messages.ERROR,'your submit is not successful')
    else:
        form=commentform()
    comments=comment.objects.filter(post=posts,status=1).order_by('created_date')
    dict={'posts':posts,'next':next_post,'prev':prev_post,'comments':comments,'form':form,'postss':postss}
    return render(request,'blog_detail.html',dict)
def blog_search(request):
    posts = post.objects.filter(published_date__lte=timezone.now(),status=1)  
    query = request.GET.get('search')  
    if query: 
        posts = posts.filter(content__icontains=query)  
    return render(request, 'blog.html', {'posts': posts})
def blog_tags(request,tag_str):
    posts=post.objects.filter(published_date__lte=timezone.now(),status=1,tags__name=tag_str)
    return render(request, 'blog.html', {'posts': posts}) 
def blog_category(request,cat_str):
    posts=post.objects.filter(published_date__lte=timezone.now(),status=1,category__name=cat_str)
    return render(request, 'blog.html', {'posts': posts})

mysite/views.py
from django.shortcuts import render,HttpResponseRedirect
from mywebsite.forms import newsletterform,contactform
from django.contrib import messages
def index_view(request):
    return render(request,'index.html')
def about_view(request):
    return render(request,'about.html')
def contact_view(request):
    if request.method=='POST':
        form=contactform(request.POST)
        if form.is_valid():
            contact=form.save(commit=False)
            contact.save()
            messages.add_message(request,messages.SUCCESS,'your submit is successful')
        else:
           messages.add_message(request,messages.ERROR,'your submit is not successful') 
    else:
        form=contactform()
    return render(request,'contact.html',{'form':form})
def newsletter_view(request):
    if request.method=='POST':
        form=newsletterform(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request,messages.SUCCESS,'your submit is successful') 
            return HttpResponseRedirect('/') 
        else :
            messages.add_message(request,messages.ERROR,'your submit is not successful')
            return HttpResponseRedirect('/')
    else:
        return HttpResponseRedirect('/')   
def custom_page_not_found(request, exception):
    return render(request, '404.html', status=404)

mysite/templates/blog.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
	<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- Title page -->
	<section class="bg-img1 txt-center p-lr-15 p-tb-92" style="background-image: url({% static 'images/bg-01.jpg' %});">
		<h2 class="ltext-105 cl0 txt-center">
			Blog
		</h2>
	</section>	


	<!-- Content page -->
	<section class="bg0 p-t-62 p-b-60">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<!-- item blog -->
						{% for post in posts %}
						<div class="p-b-63">
							<a href="{% url 'blog:blog-detail' pid=post.id %}" class="hov-img0 how-pos5-parent">
								<img src="{{post.image.url}}" alt="IMG-BLOG" style="width:800px; height:400px; object-fit:cover;">

								<div class="flex-col-c-m size-123 bg9 how-pos5">
									<span class="ltext-107 cl2 txt-center">
										{{post.published_date|date:'d'}}
									</span>

									<span class="stext-109 cl3 txt-center">
										{{post.published_date|date:'M Y'}}
									</span>
								</div>
							</a>

							<div class="p-t-32">
								<h4 class="p-b-15">
									<a href="{% url 'blog:blog-detail' pid=post.id %}" class="ltext-108 cl2 hov-cl1 trans-04">
										{{post.title}}
									</a>
								</h4>

								<p class="stext-117 cl6">
									{{post.content}}
								</p>

								<div class="flex-w flex-sb-m p-t-18">
									<span class="flex-w flex-m stext-111 cl2 p-r-30 m-tb-10">
										<span>
											<span class="cl4">By</span> {{post.author}}  
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>
										<span>
											<span class="cl4">counted views : </span>{{post.counted_views}}  
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>
										<span>
											{{post.published_date|date:'d/M/Y'}}
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>
										{% for cat in post.category.all %}
										<span>
											{{cat.name}} 
											<span class="cl12 m-l-4 m-r-6">|</span>
										</span>
										{% endfor %}
										<span>
											{{post.counted_comments}} Comments
										</span>
									</span>

									<a href="{% url 'blog:blog-detail' pid=post.id %}" class="stext-101 cl2 hov-cl1 trans-04 m-tb-10">
										Continue Reading

										<i class="fa fa-long-arrow-right m-l-9"></i>
									</a>
								</div>
							</div>
						</div>
						{% endfor %}
						<!-- Pagination -->
						<div class="flex-l-m flex-w w-full p-t-10 m-lr--7">
							{% for page in posts.paginator.page_range%}
							<a href="?page={{page}}" class="flex-c-m how-pagination1 trans-04 m-all-7 active-pagination1">
								{{page}}
							</a>
							{% endfor %}
						</div>
					</div>
				</div>

				<div class="col-md-4 col-lg-3 p-b-80">
					<div class="side-menu">
						<div class="bor17 of-hidden pos-relative">
							<form class="search-form" action="{% url 'blog:search' %}">
								<input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name="search" placeholder="Search">
								<button type="submit" class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
									<i class="zmdi zmdi-search"></i>
								</button>
							</form>
						</div>

						<div class="p-t-55">
							<h4 class="mtext-112 cl2 p-b-33">
								Categories
							</h4>

							<ul>
								{% for cat in categories %}
								<li class="bor18">
									<a href="{% url 'blog:category' cat_str=cat.name %}" class="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
										{{cat.name}}
									</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="p-t-65">
							<h4 class="mtext-112 cl2 p-b-33">
								List of Posts
							</h4>
							<ul>
								{% for post in posts %}
								<li class="flex-w flex-t p-b-30">
									<a href="{% url 'blog:blog-detail' pid=post.id %}" class="wrao-pic-w size-214 hov-ovelay1 m-r-20">
										<img src="{{post.image.url}}" alt="PRODUCT" style="width:100px; height:125px; object-fit:cover;">
									</a>

									<div class="size-215 flex-col-t p-t-8">
										<a href="{% url 'blog:blog-detail' pid=post.id %}" class="stext-116 cl8 hov-cl1 trans-04">
										{{post.title}}
										</a>

										<span class="stext-116 cl6 p-t-20">
											{{post.author}}
										</span>
									</div>
								</li>
								{% endfor %}
							</ul>		
						</div>
						<div class="p-t-50">
							<h4 class="mtext-112 cl2 p-b-27">
								Tags
							</h4>
							{% for post in posts %}
								{% for tag in post.tags.all %}
								<div class="flex-w m-r--5">
									<a href="{% url 'blog:tag' tag_str=tag.name %}" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
										{{tag.name}}
									</a>
								</div>
								{% endfor %}
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>	
{% endblock %}

mysite/templates/blog_detail.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
{% block content %}
	<!--meta-->
	<meta name="description" content="{{ posts.content|truncatewords:30 }}">
	<meta name="keywords" content="blog, travel, {{ posts.category }}">
	<meta name="author" content="{{ posts.author.username }}">
	<meta property="og:title" content="{{ posts.title }}">
	<meta property="og:description" content="{{ posts.content|truncatewords:30 }}">
	<meta property="og:image" content="{{ posts.image.url }}">
	<!-- Cart -->
	<div class="wrap-header-cart js-panel-cart">
		<div class="s-full js-hide-cart"></div>

		<div class="header-cart flex-col-l p-l-65 p-r-25">
			<div class="header-cart-title flex-w flex-sb-m p-b-8">
				<span class="mtext-103 cl2">
					Your Cart
				</span>

				<div class="fs-35 lh-10 cl2 p-lr-5 pointer hov-cl1 trans-04 js-hide-cart">
					<i class="zmdi zmdi-close"></i>
				</div>
			</div>
			
			<div class="header-cart-content flex-w js-pscroll">
				<ul class="header-cart-wrapitem w-full">
					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-01.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								White Shirt Pleat
							</a>

							<span class="header-cart-item-info">
								1 x $19.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-02.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Converse All Star
							</a>

							<span class="header-cart-item-info">
								1 x $39.00
							</span>
						</div>
					</li>

					<li class="header-cart-item flex-w flex-t m-b-12">
						<div class="header-cart-item-img">
							<img src="{% static 'images/item-cart-03.jpg' %}" alt="IMG">
						</div>

						<div class="header-cart-item-txt p-t-8">
							<a href="#" class="header-cart-item-name m-b-18 hov-cl1 trans-04">
								Nixon Porter Leather
							</a>

							<span class="header-cart-item-info">
								1 x $17.00
							</span>
						</div>
					</li>
				</ul>
				
				<div class="w-full">
					<div class="header-cart-total w-full p-tb-40">
						Total: $75.00
					</div>

					<div class="header-cart-buttons flex-w w-full">
						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-r-8 m-b-10">
							View Cart
						</a>

						<a href="shoping-cart.html" class="flex-c-m stext-101 cl0 size-107 bg3 bor2 hov-btn3 p-lr-15 trans-04 m-b-10">
							Check Out
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>


	<!-- breadcrumb -->
	<div class="container">
		<div class="bread-crumb flex-w p-l-25 p-r-15 p-t-30 p-lr-0-lg">




			
		</div>
	</div>


	<!-- Content page -->
	<section class="bg0 p-t-52 p-b-20">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-lg-9 p-b-80">
					<div class="p-r-45 p-r-0-lg">
						<!--  -->
						<div class="wrap-pic-w how-pos5-parent">
							<img src="{{posts.image.url}}" alt="IMG-BLOG" style="width:800px; height:400px; object-fit:cover;">

							<div class="flex-col-c-m size-123 bg9 how-pos5">
								<span class="ltext-107 cl2 txt-center">
									{{posts.published_date|date:'d'}}
								</span>

								<span class="stext-109 cl3 txt-center">
									{{posts.published_date|date:'M Y'}}
								</span>
							</div>
						</div>

						<div class="p-t-32">
							<span class="flex-w flex-m stext-111 cl2 p-b-19">
								<span>
									<span class="cl4">By</span> {{posts.author}}  
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>
								<span>
									<span class="cl4">counted views : </span>{{posts.counted_views}}  
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>
								<span>
									{{posts.published_date|date:'d/M/Y'}}
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>
								{% for cat in posts.category.all %}
								<span>
									{{cat.name}}  
									<span class="cl12 m-l-4 m-r-6">|</span>
								</span>
								{% endfor %}
								
								<span>
									{{posts.counted_comments}} Comments
								</span>
							</span>

							<h4 class="ltext-109 cl2 p-b-28">
								{{posts.title}}
							</h4>

							<p class="stext-117 cl6 p-b-26">
								{{posts.content}}
							</p>
						</div>

						<div class="flex-w flex-t p-t-16">
							<span class="size-216 stext-116 cl8 p-t-4">
								Tags : 
							</span>

							<div class="flex-w size-217">
								{% for tag in posts.tags.all %}
								<a href="{% url 'blog:tag' tag_str=tag.name %}" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									{{tag.name}}
								</a>
								{% endfor %}
							</div>			
						</div>
						<!-- list of comments -->
						<div class="p-t-40">
						    <h6 class="mtext-113 cl2 p-b-12">
						        Comments ({{posts.counted_comments}})
						    </h6>
						    {% if comments %}
						        {% for comment in comments %}
						            <div class="p-b-20 bor12 p-t-15 p-lr-20 m-b-20">
						                <div class="flex-w flex-t p-b-10">
						                    <div class="size-207">
						                        <div class="flex-w flex-sb-m p-b-5">
						                            <span class="mtext-107 cl2 p-r-20">
						                                {{ comment.name }}
						                            </span>
												
						                            <span class="stext-102 cl6">
						                                {{ comment.created_date |date:"d/M/Y | H:i" }}
						                            </span>
						                        </div>
											
						                        <p class="stext-102 cl6">
						                            {{ comment.subject }} – {{ comment.message }}
						                        </p>
						                    </div>
						                </div>
						            </div>
						        {% endfor %}
						    {% else %}
						        <p class="stext-107 cl6">no comment</p>
						    {% endif %}
						</div>
						<!-- comment form -->
						<div class="p-t-40">
							<h6 class="mtext-113 cl2 p-b-12">
								Leave a Comment
							</h6>

							<p class="stext-107 cl6 p-b-40">
								Your email address will not be published. Required fields are marked *
							</p>
							<form method="post" action="{% url 'blog:blog-detail' pid=posts.id %}">
								{% csrf_token %}
								<div class="bor19 size-218 m-b-20">
									<input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="name" placeholder="Name *">
								</div>

								<div class="bor19 size-218 m-b-20">
									<input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="email" placeholder="Email *">
								</div>
								<div class="form-group form-inline">
										<input type="hidden" name="post" value={{posts.id}}>
								</div>
								<div class="bor19 size-218 m-b-20">
									<input class="stext-111 cl2 plh3 size-116 p-lr-18" type="text" name="subject" placeholder="Subject *">
								</div>
								<div class="bor19 m-b-20">
									<textarea class="stext-111 cl2 plh3 size-124 p-lr-18 p-tb-15" name="message" placeholder="Comment..."></textarea>
								</div>

								

								<button type="submit" class="flex-c-m stext-101 cl0 size-125 bg3 bor2 hov-btn3 p-lr-15 trans-04">
									Post Comment
								</button>
							</form>
						</div>
					</div>
				</div>

				<div class="col-md-4 col-lg-3 p-b-80">
					<div class="side-menu">
						<div class="bor17 of-hidden pos-relative">
							<form class="search-form" action="{% url 'blog:search' %}">
								<input class="stext-103 cl2 plh4 size-116 p-l-28 p-r-55" type="text" name="search" placeholder="Search">
								<button type="submit" class="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
									<i class="zmdi zmdi-search"></i>
								</button>
							</form>
						</div>

						<div class="p-t-55">
							<h4 class="mtext-112 cl2 p-b-33">
								Categories
							</h4>

							<ul>
								{% for cat in posts.category.all %}
								<li class="bor18">
									<a href="{% url 'blog:category' cat_str=cat.name %}" class="dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4">
										{{cat.name}}
									</a>
								</li>
								{% endfor %}
							</ul>
						</div>

						<div class="p-t-65">
							<h4 class="mtext-112 cl2 p-b-33">
								List of Posts
							</h4>
							<ul>
								{% for post in postss %}
								<li class="flex-w flex-t p-b-30">
									<a href="{% url 'blog:blog-detail' pid=post.id %}" class="wrao-pic-w size-214 hov-ovelay1 m-r-20">
										<img src="{{post.image.url}}" alt="PRODUCT" style="width:100px; height:125px; object-fit:cover;">
									</a>

									<div class="size-215 flex-col-t p-t-8">
										<a href="{% url 'blog:blog-detail' pid=post.id %}" class="stext-116 cl8 hov-cl1 trans-04">
										{{post.title}}
										</a>

										<span class="stext-116 cl6 p-t-20">
											{{post.author}}
										</span>
									</div>
								</li>
								{% endfor %}
							</ul>		
						</div>
						<div class="p-t-50">
							<h4 class="mtext-112 cl2 p-b-27">
								Tags
							</h4>

							<div class="flex-w m-r--5">
								{% for tag in posts.tags.all %}
								<a href="{% url 'blog:tag' tag_str=tag.name %}" class="flex-c-m stext-107 cl6 size-301 bor7 p-lr-15 hov-tag1 trans-04 m-r-5 m-b-5">
									{{tag.name}}
								</a>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
				<div class="navigation-area d-flex justify-content-between align-items-center">
				    {% if prev %}
				    <div class="nav-left d-flex align-items-center">
				        <div class="thumb">
				            <a href="/blog/post-{{prev.id}}">
				                <img src="{{prev.image.url}}" style="width:100px; height:125px; object-fit:cover;" alt="">
				            </a>
				        </div>
				        <div class="detials ml-3">
				            <p>Prev Post</p>
				            <a href="/blog/post-{{prev.id}}"><h4>{{prev.title}}</h4></a>
				        </div>
				    </div>
				    {% endif %}
				
				    {% if next %}
				    <div class="nav-right d-flex align-items-center">
				        <div class="detials mr-3 text-right">
				            <p>Next Post</p>
				            <a href="/blog/post-{{next.id}}"><h4>{{next.title}}</h4></a>
				        </div>
				        <div class="thumb">
				            <a href="/blog/post-{{next.id}}">
				                <img src="{{next.image.url}}" style="width:100px; height:125px; object-fit:cover;" alt="">
				            </a>
				        </div>
				    </div>
				    {% endif %}
				</div>

			</div>
		</div>
	</section>	
{% endblock %}

mysite/templates/lastest_post.html
{% load static %}
{% load blog_tags %}
<!-- Start blog Area -->
 <div class="row d-flex justify-content-center">
	<div class="menu-content pb-60 col-lg-9">
		<div class="title text-center">
			<h1 class="mb-10">Latest posts from our Blog</h1>
		</div>
	</div>
</div>					
<div class="flex-w flex-sb-m p-b-52">
				
</div>	
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4 px-3">
    {% for post in posts %}
    <div class="col">
        <div class="single-recent-blog-post card h-100">
            <div class="thumb">
                <img class="card-img-top img-fluid" src="{{post.image.url}}" 
                     style="height: 350px; object-fit: cover;" alt="">
            </div>
            <div class="card-body">
                <a href="{% url 'blog:blog-detail' pid=post.id %}">
                    <h4 class="title">{{post.title}}</h4>
                </a>
                <p>{{post.content|truncatewords:10}}</p>
                <h6 class="date">{{post.published_date|date:'d/M/Y'}}</h6>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- End recent-blog Area -->